---
archetypedir:               "archetype"
# hostname (and path) to the root eg. http://spf13.com/
baseURL:                    "http://blog.obourgeois.me/"
# include content marked as draft
buildDrafts:                false
# include content with publishdate in the future
buildFuture:                false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs:               false
canonifyURLs:               true
# config file (default is path/config.yaml|json|toml)
config:                     "config.yml"
contentdir:                 "content"
dataDir:                    "data"
defaultExtension:           "html"
defaultLayout:              "post"
# filesystem path to write files to
destination:                ""
disableLiveReload:          false
# Do not build RSS files
disableRSS:                 false
# Do not build Sitemap file
disableSitemap:             false
# edit new content with this editor, if provided
editor:                     ""
footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: ""
languageCode:               "en-EN"
layoutdir:                  "layouts"
# Enable Logging
log:                        true
# Log File path (if set, logging enabled automatically)
logFile:                    ""
# "yaml", "toml", "json"
metaDataFormat:             "yaml"
newContentEditor:           ""
# Don't sync modification time of files
noTimes:                    false
paginate:                   10
paginatePath:               "page"
permalinks:
  post = "/:year/:month/:day/:slug/"
  code = "/:slug/"
# Pluralize titles in lists using inflect
pluralizeListTitles:         true
publishdir:                 ""
# color-codes for highlighting derived from this style
pygmentsStyle:              "monokai"
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses:         false
# default sitemap configuration map
sitemap:
# filesystem path to read files relative from
source:                     "."
staticdir:                  "static"
# display memory and timing of different steps of the program
stepAnalysis:               false
taxonomies:
  tag: "tags"
  topic: "topics"
# theme to use (located in /themes/THEMENAME/)
theme:                      "hugo-theme-foundation5" #"hugo-theme-crisp" #"hyde-y"
title:                      "Olivier's blog"
description:                "Olivier's blog"
# if true, use /filename.html instead of /filename/
uglyURLs:                   false
# verbose output
verbose:                    false
# verbose logging
verboseLog:                 false
# watch filesystem for changes and recreate as needed
watch:                      false

disqusShortname: "obourgeoispro-github-io"
googleAnalytics: "UA-71115937-1"

params:
  # Select a syntax highight.
  # Check the Highlight.js website for options.
  highlight: "idea"

  # Sidebar social links.
  github: "obourgeoispro" # Your Github profile ID
  bitbucket: "" # Your Bitbucket profile ID
  linkedin: "obourgeois" # Your LinkedIn profile ID (from public URL)
  googleplus: "103338573272726333134" # Your Google+ profile ID
  facebook: "" # Your Facebook profile ID
  twitter: "OlivierZentak" # Your Twitter profile ID
  youtube: ""  # Your Youtube channel ID
  flattr: ""  # populate with your flattr uid

  # SEO
  bingSiteAuth: "EAE2AED6CFAD2E4D39C13E3C2E3364C2" #website property verification meta for Bing bot
  googleSiteAuth: "e3fRS3IkyqIQqgoee6387qwd8QmblCDpFuGHxKD0gS4" #website property verification meta for Google bot
---