params:
  # Select a syntax highlight style.
  # Check the Highlight.js website for available options.
  highlight: "idea"

  # Top bar social links.
  github: "" # Your Github profile ID
  bitbucket: "" # Your Bitbucket profile ID
  linkedin: "" # Your LinkedIn profile ID (from public URL)
  googleplus: "" # Your Google+ profile ID
  facebook: "" # Your Facebook profile ID
  twitter: "" # Your Twitter profile ID
  youtube: ""  # Your Youtube channel ID
  flattr: ""  # populate with your Flattr uid

  # SEO
  bingSiteAuth: "" #website property verification meta for Bing bot
  googleSiteAuth: "" #website property verification meta for Google bot
